name: Get Stats
on:
  push:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  dev-to-stats:
    runs-on: ubuntu-latest
    name: Get Stats from Dev.to
    steps:
    - uses: actions/checkout@v2
    - name: Get Dev.to Stats
      uses: kasuboski/dev-to-stats-action@v1
      with:
        apiKey: ${{ secrets.API_KEY }}
    - name: Move stats file
      id: commit-stats
      run: |
        mkdir -p stats
        mv dev-to-stats/stats.json stats/dev-to.json
        rm -rf dev-to-stats/
    - name: Push Changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Actions
        author_email: josh.kasuboski@gmail.com
        message: "Update stats"
        add: stats/dev-to.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}